//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kutuphane.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Messages
    {
        public int Id { get; set; }
        public string PostedByMember { get; set; }
        public string GetedByMember { get; set; }
        public string Subject { get; set; }
        public string MessageContent { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
