//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kutuphane.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Penalties
    {
        public int Id { get; set; }
        public Nullable<int> MemberId { get; set; }
        public Nullable<int> TransactionId { get; set; }
        public Nullable<System.DateTime> StartingDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<decimal> Debt { get; set; }
    
        public virtual Members Members { get; set; }
        public virtual Transactions Transactions { get; set; }
    }
}
